### ISSUE TITLE
npm start fails after cloning it from git

### ISSUE THREAD

**Issue by bimalkjha** [kloener/ibm-db-electron#1]
/Users/bimaljha/nodework/installs/ibm-db-electron> npm start

> ibm-db-electron@1.0.0 start /Users/bimaljha/nodework/installs/ibm-db-electron
> electron .

sh: electron: command not found

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ibm-db-electron@1.0.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ibm-db-electron@1.0.0 start script 'electron .'.

**Comment by bimalkjha** [comment]
/Users/bimaljha/nodework/installs/ibm-db-electron> npm run build:mac

> ibm-db-electron@1.0.0 build:mac /Users/bimaljha/nodework/installs/ibm-db-electron
> build -m --x64 --dir

sh: build: command not found

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:mac"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ibm-db-electron@1.0.0 build:mac: `build -m --x64 --dir`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ibm-db-electron@1.0.0 build:mac script 'build -m --x64 --dir'.

**Comment by kloener** [comment]
Hi @bimalkjha 
you have to call `npm install` before you can run or build the application.

**Comment by kloener** [comment]
Hi @bimalkjha did npm install helped to fix the problem?

**Comment by bimalkjha** [comment]
yes, it resolved. Thanks.
